# Generated by Django 4.2.3 on 2024-04-29 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat_app', '0003_alter_chatmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchatprofilemodel',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='chat-uid'),
        ),
        migrations.AlterField(
            model_name='userchatprofilemodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chatprofile', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
