# Generated by Django 4.0.4 on 2023-05-14 12:06
import csv
from django.db import migrations


def parse_cities(apps, schema_editor):
    City = apps.get_model('city_app', 'City')

    with open('cities_cleaned.csv', encoding='utf-8', newline='') as csvfile:
        reader = csv.reader(csvfile, delimiter=',', quotechar='|',)

        for row in reader:
            city, *region = row
            city = ''.join(city).strip().replace('"', '').replace("'", "").replace(chr(0x00), "")

            region = ','.join(region).strip().replace('"', '').replace("'", "").replace(chr(0x00), "")

            c = City.objects.create(city=city, region=region)


class Migration(migrations.Migration):

    dependencies = [
        ('city_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(parse_cities),
    ]
