# Generated by Django 4.0.4 on 2023-04-05 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='level_foreign_language',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'A0'), (1, 'A1'), (2, 'A2'), (3, 'B1'), (4, 'B2'), (5, 'C1')], default=0, verbose_name='уровень иностранного языка'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Мужчина'), (1, 'Женщина')], default=0, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='level_of_education',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'среднее'), (1, 'СПО'), (2, 'высшее бакалавриат'), (3, 'высшее специалитет'), (4, 'высшее магистратура'), (5, 'высшее ученая степень')], default=0, verbose_name='Уровень образования'),
        ),
    ]
