# Generated by Django 4.0.4 on 2023-02-20 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Мужчина', 0), ('Женщина', 1)], default='Мужчина', max_length=10, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='level_of_education',
            field=models.CharField(blank=True, choices=[('среднее', 0), ('СПО', 1), ('высшее бакалавриат', 2), ('высшее специалитет', 3), ('высшее магистратура', 4), ('высшее ученая степень', 5)], max_length=100, verbose_name='Уровень образования'),
        ),
    ]
