# Generated by Django 4.0.4 on 2023-07-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0002_profile_level_foreign_language_alter_profile_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=100, verbose_name='Email'),
        ),
    ]
