# Generated by Django 4.0.4 on 2022-06-16 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users_app', '0003_alter_customuser_role'),
        ('profile_app', '0003_remove_profile_id_alter_profile_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile_company', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
                ('company_name', models.CharField(blank=True, max_length=100, verbose_name='название компании')),
                ('about_company', models.TextField(verbose_name='о компании')),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
    ]
