# Generated by Django 4.0.4 on 2023-07-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0003_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='salary_max',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='salary_min',
        ),
        migrations.AddField(
            model_name='profile',
            name='desired_salary',
            field=models.IntegerField(blank=True, null=True, verbose_name='Желаемая зарплата'),
        ),
    ]
