# Generated by Django 4.0.4 on 2023-07-16 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0004_remove_profile_salary_max_remove_profile_salary_min_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='skills',
        ),
        migrations.AddField(
            model_name='profile',
            name='about_me',
            field=models.TextField(blank=True, max_length=2000, verbose_name='О себе'),
        ),
    ]
