# Generated by Django 4.0.4 on 2022-06-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0004_company_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='about_company',
            field=models.TextField(blank=True, verbose_name='о компании'),
        ),
    ]
