# Generated by Django 4.0.4 on 2023-07-18 18:01

from django.db import migrations, models
import django.db.models.deletion
import profile_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0005_remove_profile_skills_profile_about_me'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='diplomas_certificates',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='edu_institution',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='level_of_education',
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edu_institution', models.CharField(blank=True, max_length=100, verbose_name='Учебное заведение')),
                ('speciality', models.CharField(blank=True, max_length=200, verbose_name='название специальности')),
                ('level_of_education', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'среднее'), (1, 'СПО'), (2, 'высшее бакалавриат'), (3, 'высшее специалитет'), (4, 'высшее магистратура'), (5, 'высшее ученая степень')], default=0, verbose_name='Уровень образования')),
                ('year_of_start_edu', models.DateTimeField(blank=True, verbose_name='год начала обучения')),
                ('year_of_end_edu', models.DateTimeField(blank=True, verbose_name='год окончания обучения')),
                ('diploma_certificate', models.FileField(blank=True, upload_to=profile_app.models.user_directory_path, verbose_name='Диплом или сертификат')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='profile_app.profile', verbose_name='пользователь')),
            ],
        ),
    ]
