# Generated by Django 4.0.4 on 2022-06-16 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0005_alter_company_about_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='foto',
            field=models.ImageField(blank=True, height_field=300, upload_to='', verbose_name='фото', width_field=300),
        ),
    ]
