# Generated by Django 4.0.4 on 2023-07-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0006_remove_profile_diplomas_certificates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='year_of_end_edu',
            field=models.DateField(blank=True, null=True, verbose_name='год окончания обучения'),
        ),
        migrations.AlterField(
            model_name='education',
            name='year_of_start_edu',
            field=models.DateField(blank=True, null=True, verbose_name='год начала обучения'),
        ),
    ]
