# Generated by Django 4.0.4 on 2023-07-18 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0007_alter_education_year_of_end_edu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='profile_app.profile', verbose_name='пользователь'),
        ),
        migrations.AlterField(
            model_name='education',
            name='year_of_end_edu',
            field=models.DateField(blank=True, default='2020-01-01', verbose_name='год окончания обучения'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='education',
            name='year_of_start_edu',
            field=models.DateField(blank=True, default='2020-01-01', verbose_name='год начала обучения'),
            preserve_default=False,
        ),
    ]
