# Generated by Django 4.0.4 on 2022-06-16 21:52

from django.db import migrations, models
import profile_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0008_alter_profile_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='foto',
            field=models.ImageField(blank=True, upload_to=profile_app.models.user_directory_path, verbose_name='фото'),
        ),
    ]
