# Generated by Django 4.0.4 on 2023-07-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0009_company_city_company_count_of_employees_company_inn'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='field_of_activity',
            field=models.CharField(blank=True, max_length=150, verbose_name='Сфера деятельности'),
        ),
    ]
