# Generated by Django 4.0.4 on 2022-06-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0010_rename_foto_profile_photo_alter_profile_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='career_objective',
            field=models.DateField(blank=True, null=True, verbose_name='Желаемая должность'),
        ),
        migrations.AddField(
            model_name='profile',
            name='diplomas_certificates',
            field=models.CharField(blank=True, max_length=100, verbose_name='Дипломы и сертификаты'),
        ),
        migrations.AddField(
            model_name='profile',
            name='edu_institution',
            field=models.CharField(blank=True, max_length=100, verbose_name='Учебное заведение'),
        ),
        migrations.AddField(
            model_name='profile',
            name='level_of_education',
            field=models.CharField(blank=True, choices=[('среднее', 'среднее'), ('СПО', 'СПО'), ('высшее', 'высшее')], max_length=100, verbose_name='Уровень образования'),
        ),
        migrations.AddField(
            model_name='profile',
            name='patronymic',
            field=models.CharField(blank=True, max_length=100, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='profile',
            name='salary_max',
            field=models.IntegerField(blank=True, max_length=100000000, null=True, verbose_name='Максимальная зарплата'),
        ),
        migrations.AddField(
            model_name='profile',
            name='salary_min',
            field=models.IntegerField(blank=True, max_length=100000000, null=True, verbose_name='Минимальная зарплата'),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='profile',
            name='work_experience',
            field=models.IntegerField(blank=True, max_length=120, null=True, verbose_name='Опыт работы'),
        ),
    ]
