# Generated by Django 4.0.4 on 2023-07-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0010_company_field_of_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='city',
        ),
        migrations.AddField(
            model_name='company',
            name='region',
            field=models.CharField(blank=True, max_length=50, verbose_name='Регион регистрации компании'),
        ),
    ]
