# Generated by Django 4.0.4 on 2023-07-27 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0011_remove_company_city_company_region'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'companies'},
        ),
    ]
