# Generated by Django 4.0.4 on 2022-06-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0011_profile_career_objective_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Навыки'),
        ),
    ]
