# Generated by Django 4.0.4 on 2023-07-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0012_alter_company_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=100, verbose_name='Email компании'),
        ),
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон компании'),
        ),
        migrations.AddField(
            model_name='company',
            name='site',
            field=models.CharField(blank=True, max_length=200, verbose_name='Сайт компании'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='profile',
            name='site',
            field=models.CharField(blank=True, max_length=200, verbose_name='Сайт портфолио'),
        ),
    ]
