# Generated by Django 4.0.4 on 2022-06-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0012_alter_profile_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='career_objective',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Желаемая должность'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='salary_max',
            field=models.IntegerField(blank=True, null=True, verbose_name='Максимальная зарплата'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='salary_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='Минимальная зарплата'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='work_experience',
            field=models.IntegerField(blank=True, null=True, verbose_name='Опыт работы'),
        ),
    ]
