# Generated by Django 4.0.4 on 2023-08-06 20:44

from django.db import migrations, models
import django.db.models.deletion
import profile_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0013_company_email_company_phone_company_site_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=50, verbose_name='Регион проживания'),
        ),
        migrations.AddField(
            model_name='profile',
            name='relocate',
            field=models.BooleanField(default=False, verbose_name='Готовность к переезду'),
        ),
        migrations.AlterField(
            model_name='education',
            name='diploma_certificate',
            field=models.FileField(blank=True, upload_to=profile_app.models.user_profile_directory_path, verbose_name='Диплом или сертификат'),
        ),
        migrations.AlterField(
            model_name='education',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', related_query_name='education', to='profile_app.profile', verbose_name='профиль пользователя'),
        ),
    ]
