# Generated by Django 4.0.4 on 2023-08-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0015_alter_education_year_of_end_edu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.BooleanField(blank=True, choices=[(0, 'Мужчина'), (1, 'Женщина')], default=False, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='relocate',
            field=models.BooleanField(blank=True, default=False, verbose_name='Готовность к переезду'),
        ),
    ]
