# Generated by Django 4.0.4 on 2023-08-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0016_alter_profile_gender_alter_profile_relocate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.BooleanField(blank=True, default=False, verbose_name='Пол'),
        ),
    ]
