# Generated by Django 4.0.4 on 2023-08-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0019_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.BooleanField(blank=True, choices=[(False, 'Мужчина'), (True, 'Женщина')], default=False, null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='relocate',
            field=models.BooleanField(blank=True, choices=[(False, 'Готов'), (True, 'Не готов')], default=False, null=True, verbose_name='Готовность к переезду'),
        ),
    ]
