# Generated by Django 4.0.4 on 2023-08-08 19:17

from django.db import migrations
import profile_app.models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0020_alter_profile_gender_alter_profile_relocate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='work_experience',
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to=profile_app.models.user_directory_path, verbose_name='фото'),
        ),
    ]
