# Generated by Django 4.0.4 on 2023-08-08 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0021_remove_profile_work_experience_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='desired_salary',
            field=models.IntegerField(blank=True, default=1000, verbose_name='Желаемая зарплата'),
        ),
    ]
