# Generated by Django 4.0.4 on 2023-08-09 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0022_alter_profile_desired_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=150, verbose_name='Название компании')),
                ('type_employment', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Полная занятость'), (1, 'Частичная занятость'), (2, 'Стажировка'), (3, 'Практика'), (4, 'Вахта'), (5, 'Удаленная работа')], default=0, verbose_name='Тип занятости')),
                ('job_function', models.CharField(blank=True, max_length=100, verbose_name='Должность')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='Место (город) работы')),
                ('at_now_time', models.BooleanField(default=0, verbose_name='по настоящее время')),
                ('work_responsibilities', models.TextField(blank=True, verbose_name='обязанности на рабочем месте')),
                ('year_of_start_job', models.DateField(blank=True, null=True, verbose_name='год начала работы')),
                ('year_of_end_job', models.DateField(blank=True, null=True, verbose_name='год окончания работы')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exp_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exp', related_query_name='exp', to='profile_app.profile', verbose_name='профиль пользователя')),
            ],
        ),
    ]
