# Generated by Django 4.0.4 on 2023-08-09 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0023_expjob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expjob',
            old_name='exp_profile',
            new_name='profile',
        ),
    ]
