# Generated by Django 4.0.4 on 2023-08-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0026_alter_company_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='count_of_employees',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество работников'),
        ),
        migrations.AlterField(
            model_name='education',
            name='level_of_education',
            field=models.PositiveSmallIntegerField(choices=[(0, 'среднее'), (1, 'СПО'), (2, 'высшее бакалавриат'), (3, 'высшее специалитет'), (4, 'высшее магистратура'), (5, 'высшее ученая степень')], default=0, verbose_name='Уровень образования'),
        ),
        migrations.AlterField(
            model_name='expjob',
            name='type_employment',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Полная занятость'), (1, 'Частичная занятость'), (2, 'Стажировка'), (3, 'Практика'), (4, 'Вахта'), (5, 'Удаленная работа')], default=0, verbose_name='Тип занятости'),
        ),
    ]
