# Generated by Django 4.0.4 on 2022-10-22 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=150, verbose_name='Название вакансии')),
                ('salary_min', models.IntegerField(blank=True, null=True, verbose_name='Минимальная зарплата')),
                ('salary_max', models.IntegerField(blank=True, null=True, verbose_name='Максимальная зарплата')),
                ('location', models.CharField(max_length=150, verbose_name='Место положения')),
                ('responsibilities', models.TextField(verbose_name='Возможности')),
                ('requirements', models.TextField(verbose_name='Требования')),
                ('working_mode', models.CharField(max_length=200, verbose_name='Тип работы')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_app.company')),
            ],
        ),
    ]
