# Generated by Django 4.0.4 on 2022-06-28 21:49

from django.db import migrations, models
import django.db.models.deletion
import profile_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0015_company_created_at_company_logo_company_updated_at_and_more'),
        ('vacancy_app', '0002_rename_company_name_vacancy_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy_app',
            name='company',
            field=models.ForeignKey(auto_created=profile_app.models.Company, on_delete=django.db.models.deletion.CASCADE, to='profile_app.company'),
        ),
    ]
