# Generated by Django 4.0.4 on 2023-08-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy_app', '0002_alter_vacancy_options_vacancy_work_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='working_mode',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Полная занятость'), (1, 'Частичная занятость'), (2, 'Стажировка'), (3, 'Практика'), (4, 'Вахта'), (5, 'Удаленная работа')], default=0, verbose_name='Тип занятости'),
        ),
    ]
