# Generated by Django 4.0.4 on 2023-08-10 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0026_alter_company_user'),
        ('vacancy_app', '0003_alter_vacancy_working_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy', to='profile_app.company'),
        ),
    ]
