# Generated by Django 4.0.4 on 2023-08-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy_app', '0004_alter_vacancy_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='work_experience',
            field=models.IntegerField(blank=True, choices=[(0, 'Без опыта работы'), (1, 'Прошел стажировку'), (2, '1 - 3 года'), (3, 'от 3-х лет'), (4, 'от 5-ти лет'), (5, '10+ лет')], default=0, verbose_name='Опыт работы'),
        ),
    ]
