# Generated by Django 4.0.4 on 2023-08-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy_app', '0005_alter_vacancy_work_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='work_experience',
            field=models.IntegerField(choices=[(0, 'Без опыта работы'), (1, 'Прошел стажировку'), (2, '1 - 3 года'), (3, 'от 3-х лет'), (4, 'от 5-ти лет'), (5, '10+ лет')], default=0, verbose_name='Опыт работы'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='working_mode',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Полная занятость'), (1, 'Частичная занятость'), (2, 'Стажировка'), (3, 'Практика'), (4, 'Вахта'), (5, 'Удаленная работа')], default=0, verbose_name='Тип занятости'),
        ),
    ]
