# Generated by Django 4.0.4 on 2023-08-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy_app', '0007_alter_vacancy_salary_max_alter_vacancy_salary_min'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='salary_max',
            field=models.PositiveIntegerField(default=0, verbose_name='Максимальная зарплата'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary_min',
            field=models.PositiveIntegerField(default=0, verbose_name='Минимальная зарплата'),
        ),
    ]
