# Generated by Django 4.0.4 on 2023-08-18 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=150, verbose_name='Название вакансии')),
                ('salary_min', models.PositiveIntegerField(default=0, verbose_name='Минимальная зарплата')),
                ('salary_max', models.PositiveIntegerField(default=0, verbose_name='Максимальная зарплата')),
                ('location', models.CharField(max_length=150, verbose_name='Место положения')),
                ('responsibilities', models.TextField(verbose_name='Условия')),
                ('requirements', models.TextField(verbose_name='Требования')),
                ('work_experience', models.IntegerField(choices=[(0, 'Без опыта работы'), (1, 'Прошел стажировку'), (2, '1 - 3 года'), (3, 'от 3-х лет'), (4, 'от 5-ти лет'), (5, '10+ лет')], default=0, verbose_name='Опыт работы')),
                ('working_mode', models.PositiveSmallIntegerField(choices=[(0, 'Полная занятость'), (1, 'Частичная занятость'), (2, 'Стажировка'), (3, 'Практика'), (4, 'Вахта'), (5, 'Удаленная работа')], default=0, verbose_name='Тип занятости')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy', to='profile_app.company')),
            ],
            options={
                'verbose_name_plural': 'vacancies',
            },
        ),
    ]
